let read_file path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s
;;

let unquote s =
  let s = String.trim s in
  let n = String.length s in
  if
    n >= 2
    && ((Char.equal s.[0] '\'' && Char.equal s.[n - 1] '\'')
        || (Char.equal s.[0] '"' && Char.equal s.[n - 1] '"'))
  then String.sub s 1 (n - 2)
  else s
;;

let parse_frontmatter content =
  let lines = String.split_on_char '\n' content in
  match lines with
  | first :: rest when String.equal (String.trim first) "---" ->
    let rec collect meta = function
      | [] -> None
      | l :: tl when String.equal (String.trim l) "---" -> Some (meta, tl)
      | l :: tl ->
        let meta =
          match String.index_opt l ':' with
          | Some i ->
            let k = String.trim (String.sub l 0 i) in
            let v = unquote (String.sub l (i + 1) (String.length l - i - 1)) in
            (k, v) :: meta
          | None -> meta
        in
        collect meta tl
    in
    (match collect [] rest with
     | Some (meta, body_lines) -> List.rev meta, String.concat "\n" body_lines
     | None -> [], content)
  | _ -> [], content
;;

let get meta k =
  try List.assoc k meta with
  | Not_found -> ""
;;

let () =
  let dir = if Array.length Sys.argv > 1 then Sys.argv.(1) else "." in
  let files =
    Sys.readdir dir
    |> Array.to_list
    |> List.filter (fun f -> Filename.check_suffix f ".md")
    |> List.sort compare
  in
  let buf = Buffer.create 4096 in
  Buffer.add_string buf "(* GENERATED by gen.ml — do not edit. *)\n";
  Buffer.add_string
    buf
    "type t = { slug : string; title : string; date : string; description : string; html \
     : string }\n";
  Buffer.add_string buf "let posts = [\n";
  List.iter
    (fun f ->
       let content = read_file (Filename.concat dir f) in
       let meta, body = parse_frontmatter content in
       let slug = Filename.chop_suffix f ".md" in
       let html = Omd.to_html (Omd.of_string body) in
       Buffer.add_string
         buf
         (Printf.sprintf
            "  { slug=%S; title=%S; date=%S; description=%S; html=%S };\n"
            slug
            (get meta "title")
            (get meta "date")
            (get meta "description")
            html))
    files;
  Buffer.add_string buf "]\n";
  print_string (Buffer.contents buf)
;;
